// Unique SEO-rich introductions for each Nigerian city
// Used on city directory pages for unique content signals

export function getCityIntro(cityName: string): string {
  const intros: Record<string, string> = {
    'Aba': `Aba is the commercial nerve centre of Abia State and one of the largest trading hubs in West Africa. Famous for its Ariaria International Market and a thriving manufacturing sector, the city is home to thousands of small businesses specialising in leather goods, textiles, plastics, and cosmetics. Whether you need a skilled tailor, a wholesale supplier, or a reliable logistics partner, Aba's entrepreneurial energy makes it one of Nigeria's most productive cities.`,

    'Abakaliki': `Abakaliki, the capital of Ebonyi State, has grown rapidly from a quiet administrative town into a bustling commercial centre. Known for its rice milling industry and vibrant local markets, the city supports a growing network of artisans, healthcare providers, and service businesses. Abakaliki's affordable cost of living and expanding infrastructure make it an attractive base for entrepreneurs across south-eastern Nigeria.`,

    'Abeokuta': `Abeokuta, the capital of Ogun State, blends rich Yoruba heritage with modern commerce. Nestled beneath the iconic Olumo Rock, the city is a gateway between Lagos and the northern states, giving local businesses access to diverse markets. From adire (tie-dye) textile workshops to construction firms and educational institutions, Abeokuta's economy is as layered as its history.`,

    'Abuja': `Abuja is Nigeria's federal capital and the seat of government, making it one of the country's most important business destinations. With well-planned districts like Wuse, Garki, Maitama, and the Central Business District, the city hosts everything from multinational offices to neighbourhood salons and restaurants. Abuja's growing population and high purchasing power create strong demand for quality services across every category.`,

    'Ado Ekiti': `Ado Ekiti, the capital of Ekiti State, is a university town with a youthful population and a growing appetite for modern services. The city's economy revolves around education, agriculture, and retail trade, with local businesses ranging from bookshops and eateries to tech repair centres and event planners. Ado Ekiti's compact size means word-of-mouth travels fast, rewarding businesses that deliver quality.`,

    'Akure': `Akure is the capital of Ondo State and a key commercial centre in south-western Nigeria. The city benefits from its position along major transport routes and a diverse economy spanning agriculture, mining, and services. Local businesses include everything from cocoa processing firms to modern salons, restaurants, and IT service providers, all serving a steadily growing urban population.`,

    'Asaba': `Asaba, the capital of Delta State, sits on the western bank of the River Niger directly opposite Onitsha. This strategic location has turned the city into a fast-growing commercial hub with new hotels, shopping centres, and residential estates. Asaba's business community includes construction companies, hospitality ventures, healthcare providers, and a vibrant entertainment scene.`,

    'Awka': `Awka is the capital of Anambra State and a city known for its skilled craftspeople and traders. While neighbouring Onitsha and Nnewi dominate heavy commerce, Awka has carved out its own niche in professional services, education, and government contracting. The city's growing middle class supports a healthy market for restaurants, salons, fitness centres, and home services.`,

    'Bauchi': `Bauchi, the capital of Bauchi State, is a historic city in north-eastern Nigeria with deep cultural roots and a growing modern economy. The city serves as a regional hub for agriculture, livestock trading, and retail commerce. Local businesses range from grain merchants and butcheries to pharmacies, tailoring shops, and mobile phone repair centres, all catering to a large and loyal customer base.`,

    'Benin City': `Benin City, the capital of Edo State, is one of Nigeria's oldest and most culturally significant cities. Beyond its famous bronze-casting heritage, the city is a thriving commercial centre with strong sectors in rubber processing, food production, and retail trade. Benin City's business landscape includes everything from auto parts dealers and fashion designers to hospitals, law firms, and tech startups.`,

    'Birnin Kebbi': `Birnin Kebbi is the capital of Kebbi State and a major agricultural centre in north-western Nigeria. The city is renowned for its rice farming and fishing industries along the Niger and Rima rivers. Local businesses serve both the farming community and the growing urban population, with services ranging from agricultural equipment suppliers to restaurants, pharmacies, and building material shops.`,

    'Calabar': `Calabar, the capital of Cross River State, is widely regarded as one of Nigeria's cleanest and most tourist-friendly cities. Famous for the annual Calabar Carnival and its beautiful waterfront, the city has a thriving hospitality and entertainment sector. Local businesses benefit from steady tourist traffic and a quality-conscious population that values good food, fashion, wellness, and professional services.`,

    'Enugu': `Enugu, the capital of Enugu State, was once the heart of Nigeria's coal mining industry and remains a major commercial centre in the south-east. Known as the "Coal City," Enugu today is better recognised for its universities, tech community, and vibrant food scene. The city's business directory spans IT firms, medical centres, real estate agencies, restaurants, and a growing number of creative enterprises.`,

    'Gombe': `Gombe, the capital of Gombe State, is a rapidly developing city in north-eastern Nigeria. Positioned at the crossroads of several major highways, the city serves as a trading hub for the surrounding agricultural region. Local businesses include grain dealers, livestock markets, pharmacies, tailoring workshops, and an increasing number of modern retail and service establishments.`,

    'Gusau': `Gusau is the capital of Zamfara State and a commercial centre for the surrounding farming communities. The city's economy is anchored by agriculture and livestock trading, with a growing retail and services sector. Businesses in Gusau range from food processing and building materials to healthcare clinics, schools, and mobile technology shops serving the city's expanding population.`,

    'Ibadan': `Ibadan is the capital of Oyo State and one of the largest cities in West Africa by geographical area. With a metropolitan population of several million, the city offers enormous market potential across every business category. From the famous Bodija Market and Dugbe commercial district to the university town of UI, Ibadan's economy supports everything from large-scale trading to neighbourhood services like salons, mechanics, and food vendors.`,

    'Ilorin': `Ilorin, the capital of Kwara State, occupies a unique position at the cultural crossroads of northern and southern Nigeria. This gives the city a diverse population and a broad-based economy spanning agriculture, manufacturing, and services. Ilorin's business community includes textile traders, food processors, healthcare providers, educational institutions, and a growing number of tech-savvy entrepreneurs.`,

    'Jalingo': `Jalingo is the capital of Taraba State and a gateway to some of Nigeria's most scenic landscapes. The city's economy is driven by agriculture, particularly yam and cassava farming, with a growing services sector. Local businesses include agricultural suppliers, building material dealers, restaurants, healthcare clinics, and retail shops serving both the urban population and surrounding rural communities.`,

    'Jos': `Jos, the capital of Plateau State, is known for its cool climate and scenic tin-mining heritage. Sitting at over 1,200 metres above sea level, the city attracts visitors and residents who appreciate its temperate weather. Jos has a diverse economy with strengths in agriculture, tourism, education, and technology, supporting businesses from farm-to-table restaurants and boutique hotels to IT training centres and artisan workshops.`,

    'Kaduna': `Kaduna is the capital of Kaduna State and one of northern Nigeria's most important industrial and commercial cities. With a large and diverse population, the city supports a wide range of businesses from textile factories and food processing plants to modern shopping centres, hospitals, and professional service firms. Kaduna's strategic location on the Abuja-Kano corridor ensures strong trade connections in every direction.`,

    'Kano': `Kano is the largest city in northern Nigeria and one of the oldest trading centres in West Africa, with commercial traditions stretching back over a thousand years. The city's famous dye pits, leather tanneries, and groundnut pyramids have given way to a modern economy that includes manufacturing, banking, telecommunications, and retail. Kano's massive population makes it a prime market for every type of business.`,

    'Katsina': `Katsina, the capital of Katsina State, is a historic city with deep roots in trans-Saharan trade. Today, the city's economy centres on agriculture, livestock, and retail commerce. Local businesses range from grain merchants and textile traders to modern pharmacies, restaurants, and construction firms. Katsina's growing infrastructure and educational institutions are creating new opportunities for service-oriented entrepreneurs.`,

    'Lafia': `Lafia is the capital of Nasarawa State and a rapidly growing city benefiting from its proximity to Abuja. Many professionals who work in the federal capital choose to live in Lafia for its lower cost of living, creating demand for quality local services. The city's business landscape includes real estate developers, restaurants, healthcare providers, schools, and retail shops catering to an increasingly urban population.`,

    'Lagos': `Lagos is Nigeria's economic powerhouse and the largest city in Africa, home to over 20 million people and the country's busiest port, stock exchange, and tech ecosystem. From the high-rises of Victoria Island and the markets of Balogun to the creative studios of Yaba and the industrial zones of Ikeja, Lagos offers unmatched business diversity. Every service imaginable thrives here, making it the ultimate directory for Nigerian commerce.`,

    'Lokoja': `Lokoja, the capital of Kogi State, holds the historic distinction of being the first administrative capital of modern Nigeria. Situated at the confluence of the Niger and Benue rivers, the city is a natural crossroads for trade between northern and southern Nigeria. Local businesses include transport companies, hospitality ventures, agricultural traders, and a growing number of professional service providers.`,

    'Maiduguri': `Maiduguri is the capital of Borno State and the largest city in north-eastern Nigeria. Despite past security challenges, the city's resilient business community continues to drive commerce in agriculture, livestock, and retail trade. Maiduguri's famous Monday Market is one of the largest in the region, and the city supports a wide range of businesses from healthcare clinics and schools to restaurants and building material suppliers.`,

    'Makurdi': `Makurdi, the capital of Benue State, is known as the "Food Basket of the Nation" thanks to the surrounding agricultural abundance. The city sits along the Benue River and serves as a major trading point for yams, citrus fruits, and sesame seeds. Local businesses include food processors, logistics companies, restaurants, healthcare providers, and a growing retail sector serving the city's expanding population.`,

    'Minna': `Minna is the capital of Niger State and a city experiencing rapid growth due to its proximity to Abuja. The city's economy blends traditional agriculture with modern services, and its affordable real estate has attracted both residents and businesses from the federal capital. Minna's directory includes construction companies, schools, healthcare clinics, restaurants, and retail shops serving a diverse and growing community.`,

    'Nnewi': `Nnewi in Anambra State is Nigeria's unofficial manufacturing capital, famous for producing auto parts, plastics, and electrical components. The city's industrious Igbo entrepreneurs have built a remarkable ecosystem of factories, trading companies, and support services. Beyond manufacturing, Nnewi supports a full range of local businesses including banks, hospitals, schools, restaurants, and professional service firms.`,

    'Onitsha': `Onitsha is home to the famous Onitsha Main Market, one of the largest markets in West Africa, and serves as a major commercial hub in Anambra State. The city's economy revolves around wholesale and retail trade, with businesses dealing in everything from electronics and textiles to building materials and pharmaceuticals. Onitsha's strategic location on the River Niger makes it a critical distribution point for goods across southern Nigeria.`,

    'Osogbo': `Osogbo, the capital of Osun State, is a city where traditional Yoruba culture meets modern commerce. Home to the UNESCO-listed Sacred Grove of Osun-Osogbo, the city attracts cultural tourists while supporting a diverse local economy. Businesses in Osogbo range from textile and fashion enterprises to healthcare providers, educational institutions, and a growing number of tech and creative startups.`,

    'Owerri': `Owerri, the capital of Imo State, is one of the most vibrant cities in south-eastern Nigeria. Known for its lively nightlife, entertainment scene, and love of good food, the city supports a thriving hospitality sector alongside strong healthcare, education, and retail industries. Owerri's youthful population and entrepreneurial spirit make it a dynamic market for businesses of every size and category.`,

    'Port Harcourt': `Port Harcourt is the capital of Rivers State and the centre of Nigeria's oil and gas industry. The city's petroleum wealth has created a large middle class with high spending power, driving demand for quality services across every category. From the upscale restaurants and hotels of GRA to the bustling markets of Mile 1 and Rumuokoro, Port Harcourt offers diverse business opportunities in a city that never stops moving.`,

    'Sokoto': `Sokoto, the capital of Sokoto State, is the seat of the Sultanate of Sokoto and one of the most historically significant cities in northern Nigeria. The city's economy is anchored by agriculture, leather works, and trade, with a growing modern services sector. Local businesses include grain merchants, leather craftsmen, pharmacies, schools, and an increasing number of retail and hospitality establishments.`,

    'Umuahia': `Umuahia, the capital of Abia State, is a city with strong agricultural roots and a growing commercial sector. Known for its palm oil production and food processing industries, the city also supports a range of modern businesses including healthcare facilities, educational institutions, retail shops, and professional service firms. Umuahia's strategic position on the Port Harcourt-Enugu highway ensures steady commercial traffic.`,

    'Uyo': `Uyo, the capital of Akwa Ibom State, has transformed dramatically in recent years thanks to significant infrastructure investment. The city boasts modern roads, a world-class stadium, and growing commercial districts. Uyo's business community includes construction firms, hospitality ventures, healthcare providers, and retail establishments, all benefiting from the state government's commitment to urban development and economic growth.`,

    'Warri': `Warri is the commercial capital of Delta State and one of the most economically active cities in the Niger Delta region. The city's proximity to oil installations has created a diverse economy spanning petroleum services, maritime trade, and retail commerce. Warri's famous entrepreneurial spirit and cultural diversity support businesses ranging from engineering firms and logistics companies to restaurants, fashion houses, and entertainment venues.`,

    'Yenagoa': `Yenagoa, the capital of Bayelsa State, is a riverine city that has grown rapidly since the state's creation in 1996. The city's economy is closely tied to the oil and gas industry, with a growing services sector catering to industry workers and government employees. Local businesses include hotels, restaurants, healthcare clinics, construction companies, and retail shops serving the city's expanding urban population.`,

    'Yola': `Yola is the capital of Adamawa State and a gateway to the scenic Mandara Mountains and Gashaka-Gumti National Park. The city's economy combines agriculture, livestock trading, and a growing services sector. Local businesses range from farm supply stores and grain merchants to modern restaurants, pharmacies, and professional service firms, all serving a diverse population that includes both long-time residents and newcomers.`,
  }

  return intros[cityName] || `${cityName} is a vibrant Nigerian city with a growing business community. From local shops and service providers to professional firms and creative enterprises, the city offers diverse opportunities for entrepreneurs and consumers alike. Explore the full directory of businesses in ${cityName} on MyHustle.`
}
